/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticate user and return access/refresh tokens
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid credentials */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get approval rules */
        get: {
            parameters: {
                query?: {
                    objectType?: string;
                    isActive?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of approval rules */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create approval rule */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** @enum {string} */
                        objectType: "inventory_transfer" | "sale" | "purchase" | "adjustment";
                        conditions: Record<string, never>;
                        approvalLevels?: Record<string, never>[];
                        isActive?: boolean;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Approval rule created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update approval rule */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ruleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        conditions?: Record<string, never>;
                        approvalLevels?: unknown[];
                        isActive?: boolean;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Approval rule updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete approval rule */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ruleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Approval rule deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create approval request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        objectType: "inventory_transfer" | "sale" | "purchase" | "adjustment";
                        objectId: string;
                        title: string;
                        description?: string;
                        /** @enum {string} */
                        priority?: "low" | "medium" | "high" | "urgent";
                        approvalData?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description Approval request created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/requests/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pending approvals for current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of pending approval requests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get approval request by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Approval request details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/requests/{requestId}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process approval decision */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        decision: "approved" | "rejected";
                        comments?: string;
                    };
                };
            };
            responses: {
                /** @description Approval processed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/requests/{requestId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel approval request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description Approval request cancelled successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/check-required": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check if approval is required */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        objectType: "inventory_transfer" | "sale" | "purchase" | "adjustment";
                        approvalData: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description Approval requirement check result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get approval statistics */
        get: {
            parameters: {
                query?: {
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Approval statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bulk-transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bulk transfers with filtering */
        get: {
            parameters: {
                query?: {
                    status?: ("draft" | "pending" | "approved" | "in_transit" | "completed" | "cancelled")[];
                    sourceStoreId?: string;
                    destinationStoreId?: string;
                    transferType?: ("replenishment" | "allocation" | "return" | "adjustment" | "emergency")[];
                    priority?: ("low" | "normal" | "high" | "urgent")[];
                    startDate?: string;
                    endDate?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bulk transfers retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a new bulk inventory transfer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        sourceStoreId: string;
                        destinationStoreId: string;
                        title: string;
                        description?: string;
                        /** @enum {string} */
                        priority?: "low" | "normal" | "high" | "urgent";
                        /** @enum {string} */
                        transferType?: "replenishment" | "allocation" | "return" | "adjustment" | "emergency";
                        /** Format: date-time */
                        scheduledShipDate?: string;
                        /** Format: date-time */
                        scheduledReceiveDate?: string;
                        items: {
                            productId: string;
                            quantity: number;
                            unitCost?: number;
                            notes?: string;
                        }[];
                        notes?: string;
                        reference?: string;
                    };
                };
            };
            responses: {
                /** @description Bulk transfer created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid input data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bulk-transfers/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit bulk transfer for approval */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bulk transfer submitted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bulk transfer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bulk-transfers/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve bulk transfer and create individual transfers */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Bulk transfer approved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bulk transfer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bulk-transfers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bulk transfer by ID with full details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bulk transfer retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bulk transfer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bulk-transfers/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel bulk transfer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Bulk transfer cancelled successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bulk transfer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory-regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all inventory regions for the tenant */
        get: {
            parameters: {
                query?: {
                    includeStores?: boolean;
                    isActive?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Regions retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a new inventory region */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InventoryRegionCreate"];
                };
            };
            responses: {
                /** @description Region created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            message?: string;
                            data?: components["schemas"]["InventoryRegion"];
                        };
                    };
                };
                /** @description Invalid request data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory-regions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get inventory region by ID */
        get: {
            parameters: {
                query?: {
                    includeStores?: boolean;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Region retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Region not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update an inventory region */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["InventoryRegionUpdate"];
                };
            };
            responses: {
                /** @description Region updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Region not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete an inventory region */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Region deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Region not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory-regions/{id}/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get regional inventory summary */
        get: {
            parameters: {
                query?: {
                    includeDetails?: boolean;
                    productId?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Regional inventory retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Region not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory-regions/{id}/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add stores to an inventory region */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        storeIds: string[];
                    };
                };
            };
            responses: {
                /** @description Stores added to region successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Region not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Remove stores from an inventory region */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        storeIds: string[];
                    };
                };
            };
            responses: {
                /** @description Stores removed from region successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Region not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get regions for a specific store */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    storeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Store regions retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Store not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new sale transaction
         * @description Create a new sale with items, calculate totals, and update inventory
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        items: {
                            /**
                             * Format: uuid
                             * @example 123e4567-e89b-12d3-a456-426614174000
                             */
                            productId: string;
                            /** @example 2 */
                            quantity: number;
                            /** @example 29.99 */
                            unitPrice: number;
                            /** @example 0 */
                            discount?: number;
                        }[];
                        /**
                         * Format: uuid
                         * @example 123e4567-e89b-12d3-a456-426614174000
                         */
                        customerId?: string;
                        /** @example Customer requested gift wrapping */
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Sale created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Sale"];
                            /** @example Sale created successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Validation error or insufficient stock */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - Requires sale create permission */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sale by ID
         * @description Retrieve detailed information about a specific sale including items and payments
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sale ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sale retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Sale"];
                        };
                    };
                };
                /** @description Forbidden - Requires sale read permission */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sale not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /**
         * Update sale details
         * @description Update sale information such as items, discounts, or notes
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sale ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        items?: {
                            /** Format: uuid */
                            productId?: string;
                            quantity?: number;
                            unitPrice?: number;
                            /** @default 0 */
                            discount?: number;
                        }[];
                        /** @default 0 */
                        discount?: number;
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Sale updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Sale"];
                            /** @example Sale updated successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Bad request - Invalid data or sale cannot be updated */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sale not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a sale
         * @description Permanently delete a sale (admin only, for data cleanup)
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sale ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sale deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Bad request - Sale cannot be deleted */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sale not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get store sales with pagination and filters
         * @description Retrieve sales for the current store with optional filtering and pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number for pagination */
                    page?: number;
                    /** @description Number of items per page */
                    limit?: number;
                    /** @description Filter by sale status */
                    status?: "pending" | "completed" | "cancelled";
                    /** @description Filter by payment status */
                    paymentStatus?: "pending" | "partial" | "paid" | "refunded";
                    /** @description Filter sales from this date */
                    startDate?: string;
                    /** @description Filter sales until this date */
                    endDate?: string;
                    /** @description Filter by customer ID */
                    customerId?: string;
                    /** @description Search in sale number or customer name */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Store sales retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Sale"][];
                            pagination?: {
                                /** @example 1 */
                                page?: number;
                                /** @example 20 */
                                limit?: number;
                                /** @example 150 */
                                total?: number;
                                /** @example 8 */
                                totalPages?: number;
                            };
                        };
                    };
                };
                /** @description Bad request - Invalid parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process payment for a sale
         * @description Process payment for an existing sale using various payment methods
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sale ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Payment amount */
                        amount: number;
                        /**
                         * @description Payment method
                         * @enum {string}
                         */
                        method: "cash" | "card" | "bank_transfer" | "digital_wallet" | "other";
                        /** @description Payment reference or transaction ID */
                        reference?: string;
                        /** @description Payment notes */
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Payment processed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Sale"];
                            /** @example Payment processed successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Bad request - Invalid payment data or sale cannot accept payment */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sale not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a sale
         * @description Mark a sale as completed and finalize all transactions
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sale ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sale completed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Sale"];
                            /** @example Sale completed successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Bad request - Sale cannot be completed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sale not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a sale
         * @description Cancel a pending sale and restore inventory quantities
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sale ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sale cancelled successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Sale"];
                            /** @example Sale cancelled successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Bad request - Sale cannot be cancelled */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sale not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process refund for a sale
         * @description Process a partial or full refund for a completed sale
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sale ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Amount to refund */
                        refundAmount: number;
                        /** @description Reason for the refund */
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description Refund processed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Sale"];
                            /** @example Refund processed successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Bad request - Invalid refund data or sale cannot accept refund */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sale not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sales statistics for store
         * @description Retrieve sales statistics and analytics for the current store
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start date for statistics calculation (optional) */
                    startDate?: string;
                    /** @description End date for statistics calculation (optional) */
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sales statistics retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** @example 25000.5 */
                                totalSales?: number;
                                /** @example 250 */
                                totalOrders?: number;
                                /** @example 100 */
                                averageOrderValue?: number;
                                topSellingProducts?: {
                                    /** Format: uuid */
                                    productId?: string;
                                    productName?: string;
                                    totalSold?: number;
                                    revenue?: number;
                                }[];
                            };
                        };
                    };
                };
                /** @description Bad request - Invalid parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/tenant/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tenant-wide sales statistics
         * @description Retrieve aggregated sales statistics across all stores in the tenant
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start date for filtering statistics (optional) */
                    startDate?: string;
                    /** @description End date for filtering statistics (optional) */
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant sales statistics retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** @example 125000.5 */
                                totalSales?: number;
                                /** @example 1250 */
                                totalOrders?: number;
                                /** @example 100 */
                                averageOrderValue?: number;
                                topSellingProducts?: {
                                    /** Format: uuid */
                                    productId?: string;
                                    productName?: string;
                                    totalSold?: number;
                                    revenue?: number;
                                }[];
                            };
                        };
                    };
                };
                /** @description Forbidden - Requires analytics tenant-wide permission */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/tenant/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare sales performance across stores
         * @description Compare sales performance metrics between different stores in the tenant
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start date for comparison period (optional) */
                    startDate?: string;
                    /** @description End date for comparison period (optional) */
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Store sales comparison retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** Format: uuid */
                                storeId?: string;
                                storeName?: string;
                                totalSales?: number;
                                totalOrders?: number;
                                averageOrderValue?: number;
                                growthRate?: number;
                            }[];
                        };
                    };
                };
                /** @description Forbidden - Requires analytics tenant-wide permission */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/tenant/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tenant-wide sales trends
         * @description Retrieve sales trends and patterns across all stores in the tenant over time
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start date for trend analysis (optional) */
                    startDate?: string;
                    /** @description End date for trend analysis (optional) */
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sales trends retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                dailyTrends?: {
                                    /** Format: date */
                                    date?: string;
                                    totalSales?: number;
                                    totalOrders?: number;
                                }[];
                                monthlyTrends?: {
                                    month?: string;
                                    year?: number;
                                    totalSales?: number;
                                    growthRate?: number;
                                }[];
                            };
                        };
                    };
                };
                /** @description Forbidden - Requires analytics tenant-wide permission */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/tenant/inventory-turnover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get inventory turnover metrics
         * @description Calculate inventory turnover rates and efficiency metrics across all stores
         */
        get: {
            parameters: {
                query?: {
                    /** @description Time period for turnover calculation */
                    period?: "monthly" | "quarterly" | "yearly";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Inventory turnover metrics retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** @description Overall inventory turnover rate */
                                overallTurnover?: number;
                                byStore?: {
                                    storeId?: string;
                                    storeName?: string;
                                    turnoverRate?: number;
                                    avgDaysInInventory?: number;
                                }[];
                                byCategory?: {
                                    categoryId?: string;
                                    categoryName?: string;
                                    turnoverRate?: number;
                                }[];
                            };
                        };
                    };
                };
                /** @description Forbidden - Requires analytics tenant-wide permission */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/tenant/profitability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get store profitability metrics
         * @description Calculate profitability metrics and margins across all stores in the tenant
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start date for profitability analysis (optional) */
                    startDate?: string;
                    /** @description End date for profitability analysis (optional) */
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Store profitability metrics retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                overallProfitability?: {
                                    totalRevenue?: number;
                                    totalCost?: number;
                                    netProfit?: number;
                                    profitMargin?: number;
                                };
                                byStore?: {
                                    storeId?: string;
                                    storeName?: string;
                                    revenue?: number;
                                    cost?: number;
                                    profit?: number;
                                    margin?: number;
                                    rank?: number;
                                }[];
                            };
                        };
                    };
                };
                /** @description Forbidden - Requires analytics tenant-wide permission */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example false */
            success?: boolean;
            error?: string;
            details?: Record<string, never>[];
        };
        Success: {
            /** @example true */
            success?: boolean;
            data?: Record<string, never>;
            message?: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
        };
        LoginResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                user?: components["schemas"]["User"];
                /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                accessToken?: string;
                /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                refreshToken?: string;
                /** @example 3600 */
                expiresIn?: number;
            };
        };
        User: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            tenantId?: string;
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            defaultStoreId?: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email?: string;
            /** @example John */
            firstName?: string;
            /** @example Doe */
            lastName?: string;
            /** @example +1234567890 */
            phone?: string;
            /**
             * Format: uri
             * @example https://example.com/avatar.jpg
             */
            avatar?: string;
            /** @example true */
            isActive?: boolean;
            /**
             * Format: date-time
             * @example 2023-11-10T10:00:00Z
             */
            lastLoginAt?: string;
            /**
             * Format: date-time
             * @example 2023-11-10T10:00:00Z
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @example 2023-11-10T10:00:00Z
             */
            updatedAt?: string;
        };
        Tenant: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /** @example My Company */
            name?: string;
            /** @example mycompany */
            domain?: string;
            /**
             * @example {
             *       "theme": "light",
             *       "currency": "USD"
             *     }
             */
            settings?: Record<string, never>;
            /** @example true */
            isActive?: boolean;
            /**
             * Format: date-time
             * @example 2023-11-10T10:00:00Z
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @example 2023-11-10T10:00:00Z
             */
            updatedAt?: string;
        };
        Store: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            tenantId?: string;
            /** @example Main Store */
            name?: string;
            /** @example MAIN */
            code?: string;
            /** @example 123 Main St, City, State 12345 */
            address?: string;
            /** @example +1234567890 */
            phone?: string;
            /**
             * Format: email
             * @example store@example.com
             */
            email?: string;
            /**
             * @example {
             *       "timezone": "America/New_York",
             *       "currency": "USD"
             *     }
             */
            settings?: Record<string, never>;
            /** @example true */
            isActive?: boolean;
            /**
             * Format: date-time
             * @example 2023-11-10T10:00:00Z
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @example 2023-11-10T10:00:00Z
             */
            updatedAt?: string;
        };
        InventoryRegion: {
            id?: string;
            tenantId?: string;
            name?: string;
            description?: string;
            regionCode?: string;
            location?: {
                country?: string;
                state?: string;
                city?: string;
                postalCode?: string;
                latitude?: number;
                longitude?: number;
            };
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        InventoryRegionCreate: {
            name: string;
            description?: string;
            regionCode: string;
            location?: {
                country?: string;
                state?: string;
                city?: string;
                postalCode?: string;
                latitude?: number;
                longitude?: number;
            };
        };
        InventoryRegionUpdate: {
            name?: string;
            description?: string;
            regionCode?: string;
            location?: {
                country?: string;
                state?: string;
                city?: string;
                postalCode?: string;
                latitude?: number;
                longitude?: number;
            };
            isActive?: boolean;
        };
        Sale: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            storeId?: string;
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            customerId?: string;
            /** @example SALE-2023-001 */
            saleNumber?: string;
            /**
             * @example completed
             * @enum {string}
             */
            status?: "pending" | "completed" | "cancelled";
            /**
             * @example paid
             * @enum {string}
             */
            paymentStatus?: "pending" | "partial" | "paid" | "refunded";
            items?: {
                /** Format: uuid */
                productId?: string;
                productName?: string;
                quantity?: number;
                unitPrice?: number;
                /** @default 0 */
                discount: number;
                total?: number;
            }[];
            /** @example 100 */
            subtotal?: number;
            /** @example 8 */
            taxAmount?: number;
            /** @example 0 */
            discountAmount?: number;
            /** @example 108 */
            total?: number;
            payments?: {
                /** Format: uuid */
                id?: string;
                amount?: number;
                /** @enum {string} */
                method?: "cash" | "card" | "bank_transfer" | "digital_wallet" | "other";
                reference?: string;
                /** Format: date-time */
                paidAt?: string;
            }[];
            notes?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Tenant ID for multi-tenant operations */
        tenantId: string;
        /** @description Store ID for store-specific operations */
        storeId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
